import os


class Headers:

    basic = {
        "Content-Type": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IldGZlRBQ0hzYUhvQ3VML1MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL215a290cWJvY2t6dnphY2NjdWJ6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJhOWU3NTE2Yi1kMzg4LTQ3YTUtYjU1OC1lOGJiNjA5MjE4OTciLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzU2MjE0MDA3LCJpYXQiOjE3NTU2MTQwMDcsImVtYWlsIjoibGVyYWdhbjgxOUBydWh0YW4uY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImxlcmFnYW44MTlAcnVodGFuLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZnVsbF9uYW1lIjoiQWxleCIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwicHJvbW9jb2RlIjoiUE9MWU5TS0lIIiwic3ViIjoiYTllNzUxNmItZDM4OC00N2E1LWI1NTgtZThiYjYwOTIxODk3In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoiZW1haWwvc2lnbnVwIiwidGltZXN0YW1wIjoxNzI5ODU2NzQ5fV0sInNlc3Npb25faWQiOiIxYzU1ZDlhNS0zMDgwLTQyNjEtYTk5My1jODQxMjZmNGUxNjUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.nf9PdcbpH9X5DMwxZcb2yrRmClpDvW1nXlxCWJP7Vy0",
        "x-task-id": "api-1",
    }